# https://help.github.com/en/articles/metadata-syntax-for-github-actions
name: Set SemVer Variables
description: Runs a shell script and sets multiple outputs
author: payk-12
inputs:
  version:
    description: "Input 1 description"
    required: false
  increment-by:
    description: "Increment by value: major, minor, patch, none"
		default: 'patch'
    required: false
outputs:
  currentversion:
    description: "The current SemVer value"
  newversion:
    description: "The updated SemVer value"
runs:
  using: 'node12'
  main: 'index.js'
        
